name: Salesforce Release and Deployment

on:
  push:
    branches:
      - release/*  # Trigger on release branch creation
  workflow_dispatch:
    inputs:
      action:
        description: 'Select action to trigger'
        required: true
        type: choice
        options:
          - validate
          - deploy
          - both

jobs:
  validate-prod:
    runs-on: ubuntu-latest
    # Ensure validate-prod runs when 'validate' or 'both' is selected, or for release branches
    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/heads/release/') || github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'validate' || github.event.inputs.action == 'both' }}

    steps:
      # Checkout the release branch
      - name: Checkout Release Branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

# Install Node JS and related dependencies so that it can be able to read the build.xml for TestCases
      - name: 'Installing Node.js for SFDX CLI'
        uses: actions/setup-node@v4
        with:
                node-version: 21
      # Set up Salesforce CLI
      - name: Set up Salesforce CLI
        run: |
          npm install sfdx-cli

      # Authenticate to Salesforce Prod Org using Auth File
      - name: Authenticate to Salesforce Org (Auth File)
        run: |
           run: |
                  echo ${{ secrets.SFDX_DEMO }} > ./SFDX_INTEGRATION_URL.txt

            
                  npx sfdx auth:sfdxurl:store -f ./SFDX_INTEGRATION_URL.txt -s -a QA
