name: Salesforce Release and Deployment

on:
  push:
    branches:
      - demo/*  # Trigger on release branch creation
  workflow_dispatch:
    inputs:
      action:
        description: 'Select action to trigger'
        required: true
        type: choice
        options:
          - validate
          - deploy
          - both

jobs:
  validate-prod:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/heads/demo/') || github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'validate' || github.event.inputs.action == 'both' }}

    steps:
      - name: Checkout Release Branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 'Installing Node.js for SFDX CLI'
        uses: actions/setup-node@v4
        with:
          node-version: 21

      - name: Set up Salesforce CLI
        run: |
          npm install @salesforce/cli --global 

      - name: Authenticate to Salesforce Org (Auth File)
        run: |
          echo ${{ secrets.SFDX_DEMO }} > ./SFDX_INTEGRATION_URL.txt
          npx sfdx auth:sfdxurl:store -f ./SFDX_INTEGRATION_URL.txt -a prakash06

      - name: Extract Test Classes
        id: extract_tests
        run: |
          test_classes=$(grep -oP "<members>([A-Za-z0-9_]+)</members>" manifest/package.xml | sed -E 's/<members>(.*)<\/members>/\1/')
          test_classes=$(echo "$test_classes" | grep -i "Test")
          if [ -n "$test_classes" ]; then
            echo "test_classes=$test_classes" >> $GITHUB_ENV
          else
            echo "test_classes=" >> $GITHUB_ENV
          fi

      - name: Validate Delta Changes in Salesforce Prod Org
        id: validate_deployment
        run: |
          echo "Validating delta changes (new, modified, deleted components) in Salesforce Prod Org..."
          if [ -n "$test_classes" ]; then
            echo "Running specified tests: $test_classes"
            sf project deploy validate -x manifest/package.xml -o prakash06 --test-level RunSpecifiedTests --tests "$test_classes" --json
          else
            echo "No test classes found. Running with NoTestRun."
            sf project deploy validate -x manifest/package.xml -o prakash06 --test-level RunLocalTests --json
          fi
          # Capture the exit code of the validation process
          if [[ $? -eq 0 ]]; then
            echo "Validation successful"
            echo "validation_success=true" >> $GITHUB_ENV
            echo "::set-output name=validation_success::true"  # Set output value
          else
            echo "Validation failed"
            echo "validation_success=false" >> $GITHUB_ENV
            echo "::set-output name=validation_success::false"  # Set output value
            exit 1
          fi

  deploy-prod:
    runs-on: ubuntu-latest
    needs: validate-prod
    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/heads/demo/') || github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'deploy' || github.event.inputs.action == 'both' }}

    steps:
      - name: Checkout Release Branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Deploy Validated Delta Components to Salesforce Prod Org
        run: |
          echo "Deploying validated delta components to Salesforce Prod Org..."
          # Access the output from the validate-prod job
          validation_success="${{ needs.validate-prod.outputs.validation_success }}"
          
          # Only deploy if validation was successful
          if [[ "$validation_success" == "true" ]]; then
            echo "Validation successful. Proceeding with deployment."
            sf project deploy start -x manifest/package.xml -o prakash06 --test-level RunSpecifiedTests --json
          else
            echo "Validation failed. Skipping deployment."
            exit 1
          fi
