name: Salesforce Release and Deployment

on:
  push:
    branches:
      - demo/*  # Trigger on release branch creation
  workflow_dispatch:
    inputs:
      action:
        description: 'Select action to trigger'
        required: true
        type: choice
        options:
          - validate
          - validate and deploy

jobs:
  validate-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: 'Installing Node.js for SFDX CLI'
        uses: actions/setup-node@v4
        with:
          node-version: 21

      - name: Set up Salesforce CLI
        run: |
          npm install @salesforce/cli --global

      - name: Authenticate to Salesforce Org (Auth File)
        run: |
          echo ${{ secrets.SFDX_DEMO }} > ./SFDX_INTEGRATION_URL.txt
          npx sfdx auth:sfdxurl:store -f ./SFDX_INTEGRATION_URL.txt -a prakash06

      - name: Extract Test Classes
        id: extract_tests
        run: |
          test_classes=$(grep -oP "<members>([A-Za-z0-9_]+)</members>" manifest/package.xml | sed -E 's/<members>(.*)<\/members>/\1/')
          test_classes=$(echo "$test_classes" | grep -i "Test")
          if [ -n "$test_classes" ]; then
            echo "test_classes=$test_classes" >> $GITHUB_ENV
          else
            echo "test_classes=" >> $GITHUB_ENV
          fi

      - name: Validate Delta Changes in Salesforce Prod Org
        id: validate_deployment
        run: |
          echo "Validating delta changes (new, modified, deleted components) in Salesforce Prod Org..."
          if [ -n "$test_classes" ]; then
            echo "Running specified tests: $test_classes"
            sf project deploy validate -x manifest/package.xml -o prakash06 --test-level RunSpecifiedTests --tests "$test_classes" --json
          else
            echo "No test classes found. Running with NoTestRun."
            sf project deploy validate -x manifest/package.xml -o prakash06 --test-level RunLocalTests --json
          fi

          # Capture the exit code of the validation process
          if [[ $? -eq 0 ]]; then
            echo "Validation successful"
            echo "validation_success=true" > validation_result.txt  # Save success to a file
          else
            echo "Validation failed"
            echo "validation_success=false" > validation_result.txt  # Save failure to a file
            exit 1
          fi

      - name: Debug: Check validation result file before upload
        run: |
          echo "Checking if validation_result.txt exists..."
          cat validation_result.txt || echo "File not found"

      - name: Upload validation result artifact
        uses: actions/upload-artifact@v2
        with:
          name: validation-result  # Artifact name must be the same in both jobs
          path: validation_result.txt  # Path to the file to upload

  deploy-prod:
    runs-on: ubuntu-latest
    needs: validate-prod  # Ensure this job runs after validate-prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download validation result artifact
        uses: actions/download-artifact@v2
        with:
          name: validation-result  # The name of the artifact must match the upload name

      - name: Debug - Show the value of validation_success
        run: |
          echo "Reading validation result from the downloaded file..."
          if [ -f validation_result.txt ]; then
            validation_success=$(cat validation_result.txt)
            echo "Validation Success Value: $validation_success"
          else
            echo "Validation result file not found!"
            exit 1
          fi

      - name: Deploy Validated Delta Components to Salesforce Prod Org
        run: |
          echo "Deploying validated delta components to Salesforce Prod Org..."
          
          # Access the validation success value from the file
          if [ -f validation_result.txt ]; then
            validation_success=$(cat validation_result.txt)
          else
            echo "Validation result file not found, skipping deployment!"
            exit 1
          fi

          # Debug the value of validation_success
          echo "Validation Success Value: $validation_success"
          
          # Only deploy if validation was successful
          if [[ "$validation_success" == "validation_success=true" ]]; then
            echo "Validation successful. Proceeding with deployment."
            sf project deploy start -x manifest/package.xml -o prakash06 --test-level RunSpecifiedTests --json
          else
            echo "Validation failed. Skipping deployment."
            exit 1
          fi
