name: Code Analyzer

on:   
  pull_request:
    branches:
         - main
  push:
    branches: 
        - main
        - '*'
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Node 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Salesforce CLI
        run: npm install -g --force @salesforce/cli@latest

      - name: Install Code Analyzer Plugin v4.1.0
        run: sf plugins install code-analyzer

      - name: Run forcedotcom Code Analyzer action
        uses: forcedotcom/run-code-analyzer@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-arguments: '--engine pmd,eslint-lwc --target ./force-app --format json'
          results-artifact-name: sfca-results



      - name: Upload analysis results artifact
        uses: actions/upload-artifact@v4
        with:
          name: sf-code-analysis-results
          path: sfca_results.json

